[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "phasebalance"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pandas",
    "pandapower",
    "matplotlib",
    "mpltern",
    "pyspark",
    "requests",
    "pyyaml",
    "geopandas",
    "scipy",
    "scikit-learn",
    "seaborn",
    "shapely",
    "pyarrow",
    "pillow",
    "statsmodels",
    "pandera",
    "numba",
    "folium",
    "mapclassify",
    "tqdm",
    "deepdiff",
    "networkx",
]

[tool.setuptools.packages.find]
where = ["src"]
