# Jason power flow configuration
# To switch substations: change IDs and smartmeter_file

IDs: ["1056"]

Jason_settings:
  smartmeter_file: "smartmeter_15min__substation_1056_transformer_sp1_20250801_20250901.parquet"
  default_service_fuse_size: 25
  phase_ratio: [33, 20, 47]   # % of single-phase meters assigned to phase A, B, C
  phase_seed: 42               # fixed seed for reproducible phase assignment

# smartmeter_15min__substation_0670_transformer_sp1_20250801_20250901.parquet    38/32/30
# smartmeter_15min__substation_1416_transformer_sp1_20250801_20250901.parquet     40/37/23
# smartmeter_15min__substation_1354_transformer_sp2_20250801_20250901.parquet
# smartmeter_15min__substation_1299_transformer_sp1_20250801_20250901.parquet 
# smartmeter_15min__substation_1248_transformer_sp1_20250801_20250901.parquet    
# smartmeter_15min__substation_1398_transformer_sp1_20250801_20250901.parquet   49/48/3
# smartmeter_15min__substation_0579_transformer_sp1_20250801_20250901.parquet   43/40/17
# smartmeter_15min__substation_1456_transformer_sp1_20250801_20250901.parquet # something wrong with topology power flow skips since it say no loads on transformer   phase_ratio: [45, 28, 27]
# smartmeter_15min__substation_1056_transformer_sp1_20250801_20250901.parquet  33/20/47
# smartmeter_15min__substation_1457_transformer_sp1_20250801_20250901.parquet  38/41/21
# smartmeter_15min__substation_1340_transformer_sp1_20250801_20250901.parquet 42/36/22