# Jason power flow configuration
# List substations to run. Pipeline processes each one consecutively.

#IDs: ["1056","1299","1340","1398","1457","579"]

IDs: ["1456"]

defaults:
  phase_seed: 42
  default_service_fuse_size: 25
  coverage_ratio: null       # null = auto from parquet per_completed
  transformer: 1             # transformer number (sp1)
  date_range: "20250801_20250901"

substations:
  579:
    phase_ratio: [43, 40, 17]
  670:
    phase_ratio: [38, 32, 30]
  1056:
    phase_ratio: [33, 20, 47]
  1299:
    phase_ratio: [90, 5, 5]
  1248:
    phase_ratio: [38, 31, 30]
  1340:
    phase_ratio: [42, 36, 22]
  1354:
    phase_ratio: [37, 32, 31]
    transformer: 2              # only substation using sp2
  1398:
    phase_ratio: [49, 48, 3]
  1416:
    phase_ratio: [40, 37, 23]
  1456:
    phase_ratio: [45, 28, 27]
  1457:
    phase_ratio: [38, 41, 21]


